name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: building
      run: make build
    - name: running
      run: make run
    - name: clean-up
      run: make clean
